//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GunkarSogutma
{
    using System;
    using System.Collections.Generic;
    
    public partial class GReferans
    {
        public int ID { get; set; }
        public string ReferansAdı { get; set; }
        public string ReferansFotosu { get; set; }
    }
}
