//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GunkarSogutma
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GunkarSogutmaEntities10 : DbContext
    {
        public GunkarSogutmaEntities10()
            : base("name=GunkarSogutmaEntities10")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GReferans> GReferans { get; set; }
        public virtual DbSet<GUrunler> GUrunler { get; set; }
        public virtual DbSet<GirisPanel> GirisPanel { get; set; }
        public virtual DbSet<GProje> GProje { get; set; }
        public virtual DbSet<GGUrunler> GGUrunler { get; set; }
        public virtual DbSet<GKategoriler> GKategoriler { get; set; }
    }
}
